name: Run Tests

on:
  push:
    branches: [ main, hussein_unittest ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      working-directory: ./server
      run: npm install
    
    - name: Run tests
      working-directory: ./server
      run: npm test